/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: DigitalLife3D (https://sketchfab.com/DigitalLife3D)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/model-72b-juvenile-green-sea-turtle-c90a930f8b2a4cc8bc516742a0df01d9
Title: Model 72B - Juvenile Green Sea Turtle
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Object_40: THREE.Mesh;
    Object_41: THREE.Mesh;
    Object_43: THREE.Mesh;
  };
  materials: {
    greeneye: THREE.MeshStandardMaterial;
    greeneyeouter: THREE.MeshStandardMaterial;
    greenbody: THREE.MeshPhysicalMaterial;
  };
};

export function SeaTurtle(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/sea_turtle.glb") as GLTFResult;

  return (
    <group {...props} dispose={null}>
      <group position={[1.589, 4.583, -2.578]} rotation={[-0.32, 2.91, -2.6]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.038}>
          <group
            position={[-2.266, 2.989, -2.188]}
            rotation={[-Math.PI / 2, 0, -3.117]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_40.geometry}
              material={materials.greeneye}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_41.geometry}
              material={materials.greeneyeouter}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_43.geometry}
              material={materials.greenbody}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/sea_turtle.glb");
