/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: DigitalLife3D (https://sketchfab.com/DigitalLife3D)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/model-72b-juvenile-green-sea-turtle-c90a930f8b2a4cc8bc516742a0df01d9
Title: Model 72B - Juvenile Green Sea Turtle
*/

import { editable as e } from "@theatre/r3f";

import { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import {
  AnimationClip,
  Bone,
  Group,
  MeshPhysicalMaterial,
  MeshStandardMaterial,
  SkinnedMesh,
} from "three";

type GLTFResult = GLTF & {
  nodes: {
    Object_40: SkinnedMesh;
    Object_41: SkinnedMesh;
    Object_43: SkinnedMesh;
    _rootJoint: Bone;
  };
  materials: {
    greeneye: MeshStandardMaterial;
    greeneyeouter: MeshPhysicalMaterial;
    greenbody: MeshPhysicalMaterial;
  };
};

const SWIM_CYCLE_ACTION = "Swim Cycle";

type TurtleProps = JSX.IntrinsicElements["group"] & {
  isAnimating: boolean;
};

export const SeaTurtle = ({ isAnimating, ...props }: TurtleProps) => {
  const group = useRef<Group>(null);
  const { nodes, materials, animations } = useGLTF(
    "/juvenile_green_sea_turtle.glb"
  ) as GLTFResult;
  const { actions } = useAnimations<AnimationClip>(animations, group);

  useEffect(() => {
    if (!actions[SWIM_CYCLE_ACTION]) return;
    actions[SWIM_CYCLE_ACTION].startAt(0.4);
    actions[SWIM_CYCLE_ACTION].play();
    actions[SWIM_CYCLE_ACTION].paused = !isAnimating;
  }, [isAnimating]);

  return (
    <e.group
      ref={group}
      {...props}
      dispose={null}
      position={[1.589, 4.583, -2.578]}
      rotation={[-0.32, 2.91, -2.6]}
      theatreKey="Sea Turtle"
    >
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.038}
        >
          <group
            name="green_016_round5changes_johnsonfbx"
            position={[-2.266, 2.989, -2.188]}
            rotation={[-Math.PI / 2, 0, -3.117]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="green_juvenilearmature"
                  position={[-2.266, 2.989, -2.188]}
                  rotation={[-Math.PI / 2, 0, -3.117]}
                  scale={100}
                >
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_40"
                      geometry={nodes.Object_40.geometry}
                      material={materials.greeneye}
                      skeleton={nodes.Object_40.skeleton}
                    />
                    <skinnedMesh
                      name="Object_41"
                      geometry={nodes.Object_41.geometry}
                      material={materials.greeneyeouter}
                      skeleton={nodes.Object_41.skeleton}
                    />
                    <skinnedMesh
                      name="Object_43"
                      geometry={nodes.Object_43.geometry}
                      material={materials.greenbody}
                      skeleton={nodes.Object_43.skeleton}
                    />
                    <group
                      name="Object_39"
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                    <group
                      name="Object_42"
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                  </group>
                </group>
                <group
                  name="green_juvenileeye"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="green_juvenilemesh"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </e.group>
  );
};

useGLTF.preload("/juvenile_green_sea_turtle.glb");
