/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Metal: THREE.Mesh;
    Metal001: THREE.Mesh;
    Plastic002: THREE.Mesh;
    Plastic: THREE.Mesh;
    Radio: THREE.Mesh;
    Glass: THREE.Mesh;
    Glass001: THREE.Mesh;
    Plastic003: THREE.Mesh;
    Glass003: THREE.Mesh;
    Glass004: THREE.Mesh;
    Glass005: THREE.Mesh;
    Metal002: THREE.Mesh;
    Metal003: THREE.Mesh;
    Metal004: THREE.Mesh;
    Metal005: THREE.Mesh;
    Plastic001: THREE.Mesh;
    Glass002: THREE.Mesh;
    Plastic004: THREE.Mesh;
    Glass006: THREE.Mesh;
    Plastic005: THREE.Mesh;
    Plastic006: THREE.Mesh;
    Plastic007: THREE.Mesh;
    Glass007: THREE.Mesh;
    Glass008: THREE.Mesh;
    Metal006: THREE.Mesh;
    Plastic008: THREE.Mesh;
    Plastic009: THREE.Mesh;
    Metal007: THREE.Mesh;
    Metal008: THREE.Mesh;
    Glass009: THREE.Mesh;
    Glass010: THREE.Mesh;
    Metal009: THREE.Mesh;
    Metal010: THREE.Mesh;
    Metal011: THREE.Mesh;
    Plastic010: THREE.Mesh;
    Glass011: THREE.Mesh;
    Plastic011: THREE.Mesh;
    Glass012: THREE.Mesh;
    Plastic012: THREE.Mesh;
    Plastic013: THREE.Mesh;
    Glass013: THREE.Mesh;
    Glass014: THREE.Mesh;
    Metal012: THREE.Mesh;
    Glass015: THREE.Mesh;
    Glass016: THREE.Mesh;
    Plastic014: THREE.Mesh;
    Plastic015: THREE.Mesh;
    Metal013: THREE.Mesh;
    Plastic016: THREE.Mesh;
    Plastic017: THREE.Mesh;
    Plastic018: THREE.Mesh;
  };
  materials: {
    ["Material.003"]: THREE.MeshStandardMaterial;
    ["Material.006"]: THREE.MeshStandardMaterial;
    Submesh_927_Audio_01_7thTown: THREE.MeshStandardMaterial;
    Submesh_417_JunkBottle_02_7thSlum: THREE.MeshStandardMaterial;
    Submesh_41_MaterialBottlebox_01_6thUnder: THREE.MeshStandardMaterial;
    ["Glass-5"]: THREE.MeshStandardMaterial;
    ["Material.014"]: THREE.MeshStandardMaterial;
    ["Material.015"]: THREE.MeshStandardMaterial;
    ["Material.016"]: THREE.MeshStandardMaterial;
    ["Material.013"]: THREE.MeshStandardMaterial;
    ["Material.018"]: THREE.MeshStandardMaterial;
  };
};

export const Trash = (props: JSX.IntrinsicElements["group"]) => {
  const { nodes, materials } = useGLTF("/trash.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Metal"
        castShadow
        receiveShadow
        geometry={nodes.Metal.geometry}
        material={materials["Material.003"]}
        position={[-1.68, 0.352, 0.293]}
        rotation={[0, 1.12, 0]}
        scale={[0.212, 0.318, 0.212]}
      />
      <mesh
        name="Metal001"
        castShadow
        receiveShadow
        geometry={nodes.Metal001.geometry}
        material={materials["Material.003"]}
        position={[-1.642, 0.188, 0.799]}
        rotation={[1.097, -0.268, -1.096]}
        scale={[0.171, 0.257, 0.171]}
      />
      <mesh
        name="Plastic002"
        castShadow
        receiveShadow
        geometry={nodes.Plastic002.geometry}
        material={materials["Material.006"]}
        position={[-0.698, 0.208, -0.67]}
        rotation={[-0.14, -0.315, -0.426]}
        scale={0.202}
      />
      <mesh
        name="Plastic"
        castShadow
        receiveShadow
        geometry={nodes.Plastic.geometry}
        material={materials["Material.006"]}
        position={[-1.578, 0.624, -0.562]}
        rotation={[-3.082, 0.622, -3.141]}
        scale={0.116}
      />
      <mesh
        name="Radio"
        castShadow
        receiveShadow
        geometry={nodes.Radio.geometry}
        material={materials.Submesh_927_Audio_01_7thTown}
        position={[-1.58, 0.236, -0.342]}
        rotation={[2.998, -0.992, 2.772]}
        scale={0.549}
      />
      <mesh
        name="Glass"
        castShadow
        receiveShadow
        geometry={nodes.Glass.geometry}
        material={materials.Submesh_417_JunkBottle_02_7thSlum}
        position={[-1.036, 0.047, 0.065]}
        rotation={[0.122, -1.026, -1.56]}
      />
      <mesh
        name="Glass001"
        castShadow
        receiveShadow
        geometry={nodes.Glass001.geometry}
        material={materials.Submesh_417_JunkBottle_02_7thSlum}
        position={[-0.763, 0.024, 0.463]}
        rotation={[0.735, 0.891, 0.892]}
      />
      <mesh
        name="Plastic003"
        castShadow
        receiveShadow
        geometry={nodes.Plastic003.geometry}
        material={materials.Submesh_41_MaterialBottlebox_01_6thUnder}
        position={[-1.017, 0.213, -0.133]}
        rotation={[1.828, -0.07, -0.291]}
      />
      <mesh
        name="Glass003"
        castShadow
        receiveShadow
        geometry={nodes.Glass003.geometry}
        material={materials.Submesh_417_JunkBottle_02_7thSlum}
        position={[-1.422, 0.572, -0.917]}
        rotation={[2.335, 0.098, 1.866]}
      />
      <mesh
        name="Glass004"
        castShadow
        receiveShadow
        geometry={nodes.Glass004.geometry}
        material={materials["Glass-5"]}
        position={[-1.419, 0.022, 0.418]}
        rotation={[0.373, 0.37, 1.422]}
        scale={0.728}
      />
      <mesh
        name="Glass005"
        castShadow
        receiveShadow
        geometry={nodes.Glass005.geometry}
        material={materials["Glass-5"]}
        position={[-1.533, -0.011, 0.036]}
        rotation={[-1.291, 1.021, 0.479]}
        scale={0.728}
      />
      <mesh
        name="Metal002"
        castShadow
        receiveShadow
        geometry={nodes.Metal002.geometry}
        material={materials["Material.014"]}
        position={[-0.473, 0.044, -0.822]}
        rotation={[0.499, -0.785, -3.031]}
        scale={0.316}
      />
      <mesh
        name="Metal003"
        castShadow
        receiveShadow
        geometry={nodes.Metal003.geometry}
        material={materials["Material.015"]}
        position={[-0.387, 0.065, -0.494]}
        rotation={[-0.614, -0.246, 1.267]}
        scale={0.055}
      />
      <mesh
        name="Metal004"
        castShadow
        receiveShadow
        geometry={nodes.Metal004.geometry}
        material={materials["Material.016"]}
        position={[-0.725, 0.042, -0.445]}
        rotation={[-1.055, 1.471, -0.323]}
        scale={[0.05, 0.043, 0.043]}
      />
      <mesh
        name="Metal005"
        castShadow
        receiveShadow
        geometry={nodes.Metal005.geometry}
        material={materials["Material.013"]}
        position={[-0.726, 0.042, -0.443]}
        rotation={[-0.977, 1.455, -0.398]}
        scale={[0.051, 0.041, 0.04]}
      />
      <mesh
        name="Plastic001"
        castShadow
        receiveShadow
        geometry={nodes.Plastic001.geometry}
        material={materials["Material.006"]}
        position={[-1.206, 0.875, -1.397]}
        rotation={[-1.764, 0.125, 1.124]}
        scale={0.12}
      />
      <mesh
        name="Glass002"
        castShadow
        receiveShadow
        geometry={nodes.Glass002.geometry}
        material={materials.Submesh_417_JunkBottle_02_7thSlum}
        position={[-0.905, 0.027, -0.001]}
        rotation={[1.249, -1.226, -0.454]}
      />
      <mesh
        name="Plastic004"
        castShadow
        receiveShadow
        geometry={nodes.Plastic004.geometry}
        material={materials["Material.018"]}
        position={[-1.335, 0.042, -0.048]}
        rotation={[1.465, -0.132, 2.08]}
        scale={[0.049, 0.049, 0.04]}
      />
      <mesh
        name="Glass006"
        castShadow
        receiveShadow
        geometry={nodes.Glass006.geometry}
        material={materials.Submesh_417_JunkBottle_02_7thSlum}
        position={[0.947, 1.147, 0.473]}
        rotation={[0.735, 0.891, 0.892]}
      />
      <mesh
        name="Plastic005"
        castShadow
        receiveShadow
        geometry={nodes.Plastic005.geometry}
        material={materials["Material.006"]}
        position={[-1.917, 0.094, 2.978]}
        rotation={[-3.082, 0.622, -3.141]}
        scale={0.163}
      />
      <mesh
        name="Plastic006"
        castShadow
        receiveShadow
        geometry={nodes.Plastic006.geometry}
        material={materials["Material.006"]}
        position={[1.648, 1.202, 0.194]}
        rotation={[-0.056, 0.517, 0.063]}
        scale={0.079}
      />
      <mesh
        name="Plastic007"
        castShadow
        receiveShadow
        geometry={nodes.Plastic007.geometry}
        material={materials.Submesh_41_MaterialBottlebox_01_6thUnder}
        position={[0.543, 0.141, 1.933]}
        rotation={[-1.554, -1.472, -1.621]}
        scale={0.779}
      />
      <mesh
        name="Glass007"
        castShadow
        receiveShadow
        geometry={nodes.Glass007.geometry}
        material={materials.Submesh_417_JunkBottle_02_7thSlum}
        position={[0.614, 0.198, 1.853]}
        rotation={[-0.079, 0.424, -0.17]}
      />
      <mesh
        name="Glass008"
        castShadow
        receiveShadow
        geometry={nodes.Glass008.geometry}
        material={materials.Submesh_417_JunkBottle_02_7thSlum}
        position={[0.667, 0.121, 2.036]}
        rotation={[0.525, 0.703, -0.258]}
      />
      <mesh
        name="Metal006"
        castShadow
        receiveShadow
        geometry={nodes.Metal006.geometry}
        material={materials["Material.003"]}
        position={[0.442, 0.239, 3.096]}
        rotation={[-1.466, -1.137, -1.418]}
        scale={[0.171, 0.257, 0.171]}
      />
      <mesh
        name="Plastic008"
        castShadow
        receiveShadow
        geometry={nodes.Plastic008.geometry}
        material={materials["Material.006"]}
        position={[0.908, 0.103, 4.126]}
        rotation={[-0.14, -0.315, -0.426]}
        scale={0.157}
      />
      <mesh
        name="Plastic009"
        castShadow
        receiveShadow
        geometry={nodes.Plastic009.geometry}
        material={materials["Material.006"]}
        position={[1.127, 0.058, 4.263]}
        rotation={[-0.056, 0.517, 0.063]}
        scale={0.079}
      />
      <mesh
        name="Metal007"
        castShadow
        receiveShadow
        geometry={nodes.Metal007.geometry}
        material={materials["Material.003"]}
        position={[1.788, 0.302, 2.66]}
        rotation={[Math.PI, -0.807, Math.PI]}
        scale={[0.212, 0.318, 0.212]}
      />
      <mesh
        name="Metal008"
        castShadow
        receiveShadow
        geometry={nodes.Metal008.geometry}
        material={materials["Material.003"]}
        position={[1.908, 0.137, 2.166]}
        rotation={[1.945, 0.398, 2.348]}
        scale={[0.171, 0.257, 0.171]}
      />
      <mesh
        name="Glass009"
        castShadow
        receiveShadow
        geometry={nodes.Glass009.geometry}
        material={materials["Glass-5"]}
        position={[2.209, 0.779, 1.137]}
        rotation={[0.373, 0.37, 1.422]}
        scale={0.728}
      />
      <mesh
        name="Glass010"
        castShadow
        receiveShadow
        geometry={nodes.Glass010.geometry}
        material={materials["Glass-5"]}
        position={[2.178, 0.746, 0.845]}
        rotation={[-3.074, 1.203, 2.273]}
        scale={0.728}
      />
      <mesh
        name="Metal009"
        castShadow
        receiveShadow
        geometry={nodes.Metal009.geometry}
        material={materials["Material.014"]}
        position={[1.56, 1.181, 0.348]}
        rotation={[0.499, -0.785, -3.031]}
        scale={0.316}
      />
      <mesh
        name="Metal010"
        castShadow
        receiveShadow
        geometry={nodes.Metal010.geometry}
        material={materials["Material.015"]}
        position={[1.564, 1.202, 0.548]}
        rotation={[-0.614, -0.246, 1.267]}
        scale={0.055}
      />
      <mesh
        name="Metal011"
        castShadow
        receiveShadow
        geometry={nodes.Metal011.geometry}
        material={materials["Material.016"]}
        position={[1.431, 1.179, 0.515]}
        rotation={[-1.055, 1.471, -0.323]}
        scale={[0.05, 0.043, 0.043]}
      />
      <mesh
        name="Plastic010"
        castShadow
        receiveShadow
        geometry={nodes.Plastic010.geometry}
        material={materials["Material.018"]}
        position={[1.534, 0.716, 3.685]}
        rotation={[1.465, -0.132, 2.08]}
        scale={[0.049, 0.049, 0.04]}
      />
      <mesh
        name="Glass011"
        castShadow
        receiveShadow
        geometry={nodes.Glass011.geometry}
        material={materials.Submesh_417_JunkBottle_02_7thSlum}
        position={[3.041, 1.02, -0.454]}
        rotation={[3.002, -1.098, 1.353]}
        scale={0.869}
      />
      <mesh
        name="Plastic011"
        castShadow
        receiveShadow
        geometry={nodes.Plastic011.geometry}
        material={materials.Submesh_41_MaterialBottlebox_01_6thUnder}
        position={[3.195, 1.164, -0.532]}
        rotation={[1.769, 0.179, 0.693]}
        scale={0.869}
      />
      <mesh
        name="Glass012"
        castShadow
        receiveShadow
        geometry={nodes.Glass012.geometry}
        material={materials.Submesh_417_JunkBottle_02_7thSlum}
        position={[3.15, 1.003, -0.388]}
        rotation={[2.733, -0.632, 1.207]}
        scale={0.869}
      />
      <mesh
        name="Plastic012"
        castShadow
        receiveShadow
        geometry={nodes.Plastic012.geometry}
        material={materials["Material.006"]}
        position={[3.501, 0.465, -0.24]}
        rotation={[-0.621, -0.954, -0.214]}
        scale={0.202}
      />
      <mesh
        name="Plastic013"
        castShadow
        receiveShadow
        geometry={nodes.Plastic013.geometry}
        material={materials["Material.006"]}
        position={[0.522, 0.09, 2.755]}
        rotation={[-0.621, -0.954, -0.214]}
        scale={0.202}
      />
      <mesh
        name="Glass013"
        castShadow
        receiveShadow
        geometry={nodes.Glass013.geometry}
        material={materials.Submesh_417_JunkBottle_02_7thSlum}
        position={[-1.687, 1.161, 3.203]}
        rotation={[-0.261, -0.952, -1.682]}
      />
      <mesh
        name="Glass014"
        castShadow
        receiveShadow
        geometry={nodes.Glass014.geometry}
        material={materials.Submesh_417_JunkBottle_02_7thSlum}
        position={[-1.563, 1.113, 3.138]}
        rotation={[0.685, -1.246, -0.753]}
      />
      <mesh
        name="Metal012"
        castShadow
        receiveShadow
        geometry={nodes.Metal012.geometry}
        material={materials["Material.003"]}
        position={[-1.686, 0.167, 3.517]}
        rotation={[1.351, 0.497, -2.706]}
        scale={[0.171, 0.257, 0.171]}
      />
      <mesh
        name="Glass015"
        castShadow
        receiveShadow
        geometry={nodes.Glass015.geometry}
        material={materials["Glass-5"]}
        position={[0.977, 1.238, 3.444]}
        rotation={[0.373, 0.37, 1.422]}
        scale={0.728}
      />
      <mesh
        name="Glass016"
        castShadow
        receiveShadow
        geometry={nodes.Glass016.geometry}
        material={materials["Glass-5"]}
        position={[0.789, 1.232, 3.167]}
        rotation={[1.117, 0.536, -2.482]}
        scale={0.728}
      />
      <mesh
        name="Plastic014"
        castShadow
        receiveShadow
        geometry={nodes.Plastic014.geometry}
        material={materials["Material.006"]}
        position={[1.577, 1.316, 1.361]}
        rotation={[-0.14, -0.315, -0.426]}
        scale={0.157}
      />
      <mesh
        name="Plastic015"
        castShadow
        receiveShadow
        geometry={nodes.Plastic015.geometry}
        material={materials["Material.006"]}
        position={[1.796, 1.271, 1.499]}
        rotation={[-0.056, 0.517, 0.063]}
        scale={0.079}
      />
      <mesh
        name="Metal013"
        castShadow
        receiveShadow
        geometry={nodes.Metal013.geometry}
        material={materials["Material.003"]}
        position={[1.833, 1.118, 0.759]}
        rotation={[2.951, -0.802, 2.698]}
        scale={[0.171, 0.257, 0.171]}
      />
      <mesh
        name="Plastic016"
        castShadow
        receiveShadow
        geometry={nodes.Plastic016.geometry}
        material={materials["Material.006"]}
        position={[2.266, 0.065, 2.392]}
        rotation={[-0.621, -0.954, -0.214]}
        scale={0.202}
      />
      <mesh
        name="Plastic017"
        castShadow
        receiveShadow
        geometry={nodes.Plastic017.geometry}
        material={materials["Material.006"]}
        position={[1.401, 0.53, 2.802]}
        rotation={[0.853, 0.887, -0.76]}
        scale={0.157}
      />
      <mesh
        name="Plastic018"
        castShadow
        receiveShadow
        geometry={nodes.Plastic018.geometry}
        material={materials["Material.006"]}
        position={[1.055, 1.016, 2.795]}
        rotation={[-3.03, -1.12, -3.006]}
        scale={0.079}
      />
    </group>
  );
};

useGLTF.preload("/trash.glb");
